[package]
name = "ju4tc5"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["rt", "macros", "rt-multi-thread"] }
uuid = { version = "1.12.1", features = ["v4", "v7", "fast-rng"] }
serde = { version = "1.0.217", features = ["derive"] }
